### PR TITLE
Reorganize make target dependencies in Kubernetes due to failed jobs

### PR DESCRIPTION
**Pull request by vivek-koppuru**
*Issue #, if available:*

*Description of changes:*

Builds in prow are failing due to being unable to find the kubernetes/kubernetes/kubernetes folder. Reorganizing the target dependencies to ensure that we have a streamlined structure for both our presubmits and postsubmits.

Removing other unnecessary environment variables as our Makefile will construct those values based on the RELEASE. My assumption before was that if they were empty anyways, they would be set in the Makefile but that wasn't the case.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
We cool?

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
