### PR TITLE
Updated kops to 1.25.3

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*
Related to https://github.com/aws/eks-distro/issues/1472

*Description of changes:*
* Use kops 1.25.3, which eks-distro-build-tooling updated in https://github.com/aws/eks-distro-build-tooling/pull/741

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/override aws-cloud-controller-manager-1-25-presubmit
/override aws-iam-authenticator-1-25-presubmit
/override cni-plugins-1-25-presubmit
/override coredns-1-25-presubmit
/override etcd-1-25-presubmit
/override external-attacher-1-25-presubmit
/override external-provisioner-1-25-presubmit
/override external-resizer-1-25-presubmit
/override external-snapshotter-1-25-presubmit
/override kubernetes-1-25-presubmit
/override kubernetes-1-25-test-presubmit
/override kubernetes-release-1-25-presubmit
/override livenessprobe-1-25-presubmit
/override metrics-server-1-25-presubmit
/override node-driver-registrar-1-25-presubmit

these are expected to be broken for now

**Review by jaxesn — APPROVED** [review]

**Pull request merged**
