### PR TITLE
Added old attribution for cni 1-23

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
* Fix failed postsubmit build by adding old attribution to 1-23. This change cause the build failure: https://github.com/aws/eks-distro/pull/1157

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
I don't think this is why the post submit is failing.

**Comment by jaxesn** [comment]
https://github.com/aws/eks-distro/blob/main/development/kops/set_environment.sh#L77

**Comment by kschumy** [comment]
@jaxesn ah yeah I think you're right

**Comment by kschumy** [comment]
Closing to fix what Jackson suggested

**Pull request closed without merging**
