### PR TITLE
update project dependency update runbook

### PR DESCRIPTION
**Pull request by danbudris**
include note about replace directive

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by kschumy — APPROVED** [review]
/lgtm

**Comment by markapruett** [comment]
@danbudris Move to fork otherwise lgtm

**Comment by markapruett** [comment]
Moved this to fork in https://github.com/aws/eks-distro/pull/1342

**Pull request closed without merging**
