### PR TITLE
Updated aws-iam-authenticator version and added README

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*
N/A

*Description of changes:*
* Updated aws-iam-authenticator version to be 0.5.3 for all versions.
* Added README about updating aws-iam-authenticator
* Updated attribution
* Updated CHECKSUMS

### Golang version [was NOT updated](https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/a0516fb9ace571024263424f1770e6d861e65d09/go.mod#L3) by aws-iam-authenticator for this version.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

need to update all checksums

**Review by jaxesn — COMMENTED** [review]
Should be good to go, just update the other checksum files.

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
