### PR TITLE
Update external resizer 1.5.0

### PR DESCRIPTION
**Pull request by kschumy**
### Issue #, if available:

#992 

Part of #986

### Description of changes:

* Updated external resizer from v1.4.0 to [v1.5.0](https://github.com/kubernetes-csi/external-resizer/releases/tag/v1.5.0) for 1.19 - 1.23
* Updated Golang versions because it looks like they did -- https://github.com/kubernetes-csi/external-resizer/blob/v1.5.0/release-tools/prow.sh#L89
* Updated go.sum and for sure messed it up

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

because I don't think I did the dependencies update right and need Jackson to look at it

**Comment by jaxesn** [comment]
Just dont update the go.sum files, there is a periodic prow job that will do this for us

**Review by jaxesn — APPROVED** [review]

**Comment by kschumy** [comment]
/hold

until 1.18 go change done

**Pull request merged**
