### PR TITLE
Do not use BUILD_ID for RELEASE

### PR DESCRIPTION
**Pull request by TerryHowe**
We aren't going to bother using BUILD_ID for RELEASE. RELEASE will be set by Prow job to shortened SHA1.

### CODE REVIEW

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
It could be this change actually broke the 1.19 presubmit, but hard to imagine how

**Comment by jaxesn** [comment]
The failing tests are the upstream's top flaky tests. Ill rerun one more time then will manually merge.

**Comment by jaxesn** [comment]
Confirmed failures are flakes, merge manually.

**Pull request merged**
