### PR TITLE
metrics-server: fix tagging flags on go build

### PR DESCRIPTION
**Pull request by jaxesn**
*Description of changes:*

Some projects vendor their deps in github.  For these we have traditionally not run `go mod vendor` since it was unnecessary.  Turns out, even though running `go mod vendor` in a repo that already has a vendor folder changes nothing inside the repo it does change the resulting binary slightly.  Using `strings` ran against the binaries and comparing, it appears that modules downloaded into the mod cache end up having an additional h1: hash whereas when building with a locally vendor directly, these hashes are not included.

This feels pretty minor and I suspect has no impact on the execution of the binary.  Adding go mod vendor to all projects for consistency  which does change the checksums, but these checksums still match what I produce on my mac and what is produced in prow.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-distro/pull/581#" title="Author self-approved">jaxesn</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-distro).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-distro/blob/main/OWNERS)~~ [jaxesn]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
@jaxesn: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
metrics-server-1-18-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-18-presubmit/1442908163178237952) | `/test metrics-server-1-18-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=581). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:jaxesn).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@jaxesn: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
metrics-server-1-18-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-18-presubmit/1442908163178237952) | `/test metrics-server-1-18-presubmit`
metrics-server-1-20-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-20-presubmit/1442908163245346816) | `/test metrics-server-1-20-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=581). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:jaxesn).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@jaxesn: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
metrics-server-1-18-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-18-presubmit/1442908163178237952) | `/test metrics-server-1-18-presubmit`
metrics-server-1-20-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-20-presubmit/1442908163245346816) | `/test metrics-server-1-20-presubmit`
metrics-server-1-19-presubmit | a30d5c8107f9dcac6d1d6562c80e3db78fe3979d | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/581/metrics-server-1-19-presubmit/1442908163211792384) | `/test metrics-server-1-19-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=581). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:jaxesn).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-distro/pull/581#" title="Author self-approved">jaxesn</a>*, *<a href="https://github.com/aws/eks-distro/pull/581#pullrequestreview-765787735" title="LGTM">TerryHowe</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-distro).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-distro/blob/main/OWNERS)~~ [TerryHowe,jaxesn]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
New changes are detected. LGTM label has been removed.

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
