### PR TITLE
Created 1.31 foundation with updated tags and patches for k8s v1.31.0-beta.0

### PR DESCRIPTION
**Pull request by varma-maryala**
*Issue https://github.com/aws/eks-distro/issues/3214, if available:*

*Description of changes:*
1. Created the 1.31 foundation with all the git tags and public patches from 
    * K8s Patches https://gitlab.aws.dev/eks-dataplane/eks-kubernetes-patches/-/tree/mainline/patches/1.31/0-public?ref_type=heads
    * K8's version in 1.31 latest manifest(https://gitlab.aws.dev/mpvarma/aws-wesley-manifests/-/commit/18dec55b22658d02ce80b4f84e7a51541e91b59b)
    
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vineeth-bandi** [comment]
We should also add it to .github/labeler.yml to auto label 1.31 changes.

**Comment by varma-maryala** [comment]
IF you see the issue, i tagged. I have already added that label: Issue: https://github.com/aws/eks-distro/issues/3214 & PR: https://github.com/aws/eks-distro/pull/3215

**Pull request merged**
