### PR TITLE
Added 1-20 directories for components

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
Holding. Need to follow up with something before removing hold label

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
hold 🤷  ?

**Pull request merged**
