### PR TITLE
Split CSI Snapshotter

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
* See https://kubernetes-csi.github.io/docs/external-snapshotter.html
* Need this for new Golang versions

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
Prow jobs change: https://github.com/aws/eks-distro-prow-jobs/pull/266

**Comment by TerryHowe** [comment]
Hmm, 1.22 GIT_TAG missing. Probably easiest just to add it? The other one failed on checksums.

**Review by jaxesn — APPROVED** [review]
Updated checksums.

/lgtm

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
