### PR TITLE
Updated external-provisioner to 3.1.1 for 1.20 - 1.23

### LINKED ISSUE #991: kubernetes-csi/external-provisioner

### PR DESCRIPTION
**Pull request by kschumy**
### Issue #, if available:

Closes #991 

Part of #986 releases

### Description of changes:

* Updated external-provisioner to [v3.1.1](https://github.com/kubernetes-csi/external-provisioner/releases/tag/v3.1.1) for 1.20 - 1.23

/hold because idk what to do with dependencies and need Jackson's help

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — COMMENTED** [review]
Check the dep patch, its bumping the k8s version, if this new 3.1.1 version is still using that old version in their go.mod, lets keep out patch, if they have updated it to a newer kube version we can drop our patch.

**Comment by kschumy** [comment]
> Check the dep patch, its bumping the k8s version, if this new 3.1.1 version is still using that old version in their go.mod, lets keep out patch, if they have updated it to a newer kube version we can drop our patch.

I don't think there is a patch for any of these versions. It looks like there is [one for 1.19](https://github.com/aws/eks-distro/tree/main/projects/kubernetes-csi/external-provisioner/1-19), but 1.19 is incompatible with 3.1.1. Or is there something I'm missing?

**Comment by jaxesn** [comment]
Ah ok, I saw the 1.19 one and probably assumed, you should be good.

**Review by jaxesn — APPROVED** [review]

**Pull request merged**
