### PR TITLE
Changes release number of non-dev values for 1.19-2

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
Hold until this PR goes through https://github.com/aws/eks-distro/pull/253

This is step 9 in https://github.com/aws/eks-distro/blob/main/docs/contents/runbook.md

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
I think this is g2g, release when ready

**Comment by jaxesn** [comment]
The failed build should have passed if the retry logic was correct. 

https://github.com/aws/eks-distro/pull/264

**Pull request merged**
