### PR TITLE
Initial changes and patches for 1.22

### PR DESCRIPTION
**Pull request by kschumy**
*Description of changes:*
* Added patches
* Made other changes from the runbook

---

### NOTE TO FUTURE US: change etcd version to 3.5.1.
There was a [problem with this build](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/684/etcd-1-22-presubmit/1488974766579650560), and we don't want this to be blocking. 

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
I need to update the prow jobs to include 1.22. The checksums will fail, but I'll update them when they do

**Comment by kschumy** [comment]
/hold

Will need to change the checksums when they fail

**Comment by kschumy** [comment]
/hold

Jackson is changing something

**Comment by kschumy** [comment]
### Need this PR merged first: https://github.com/aws/eks-distro/pull/703

Then will update this one

**Review by jaxesn — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
