### PR TITLE
Minor change to patch subject

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-distro/pull/575#" title="Author self-approved">kschumy</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-distro).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-distro/blob/main/OWNERS)~~ [kschumy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit-tests | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit-tests/1440857988154789888) | `/test kubernetes-1-20-presubmit-tests`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit-tests | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit-tests/1440857988154789888) | `/test kubernetes-1-20-presubmit-tests`
kubernetes-1-20-presubmit | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1440857988230287360) | `/test kubernetes-1-20-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1440857988230287360) | `/test kubernetes-1-20-presubmit`
kubernetes-1-20-presubmit-tests | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit-tests/1440859371696295936) | `/test kubernetes-1-20-presubmit-tests`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit-tests | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit-tests/1440859371696295936) | `/test kubernetes-1-20-presubmit-tests`
kubernetes-1-20-presubmit | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1441160300240834560) | `/test kubernetes-1-20-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1441160300240834560) | `/test kubernetes-1-20-presubmit`
kubernetes-1-19-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-19-presubmit/1441373046924382208) | `/test kubernetes-1-19-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-20-presubmit | d932d22da4b7c33a8e6d26e0ad4fe95301598566 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1441160300240834560) | `/test kubernetes-1-20-presubmit`
kubernetes-1-19-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-19-presubmit/1441373046924382208) | `/test kubernetes-1-19-presubmit`
kubernetes-1-18-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-18-presubmit/1441373046886633472) | `/test kubernetes-1-18-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-19-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-19-presubmit/1441373046924382208) | `/test kubernetes-1-19-presubmit`
kubernetes-1-18-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-18-presubmit/1441373046886633472) | `/test kubernetes-1-18-presubmit`
kubernetes-1-20-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1441373046987296768) | `/test kubernetes-1-20-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@kschumy: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kubernetes-1-19-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-19-presubmit/1441373046924382208) | `/test kubernetes-1-19-presubmit`
kubernetes-1-18-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-18-presubmit/1441373046886633472) | `/test kubernetes-1-18-presubmit`
kubernetes-1-20-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-20-presubmit/1441373046987296768) | `/test kubernetes-1-20-presubmit`
kubernetes-1-21-presubmit | 5978e652e1a8ca7e4dc1cdb2c0132d8e2622f713 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-distro/575/kubernetes-1-21-presubmit/1441373047029239808) | `/test kubernetes-1-21-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-distro&pr=575). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:kschumy).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-distro/pull/575#pullrequestreview-763434829" title="LGTM">jaxesn</a>*, *<a href="https://github.com/aws/eks-distro/pull/575#" title="Author self-approved">kschumy</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-distro).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-distro/blob/main/OWNERS)~~ [jaxesn,kschumy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
