### PR TITLE
Update external attacher

### PR DESCRIPTION
**Pull request by kschumy**
*Description of changes:*
* Fixed incorrect golang version for CSI external attacher for 1.22.
* For 1.18 - 1.21, upgraded CSI external attacher from v3.2.0 to v3.4.0
  * Everything was copied from 1.22
* Decision based on [compatibility table](https://kubernetes-csi.github.io/docs/external-attacher.html)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
```
+ go build -trimpath -a -ldflags '-s -w -buildid= -extldflags -static ' -o /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-attacher/_output/1-18/bin/external-attacher/linux-amd64/csi-attacher ./cmd/csi-attacher
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
make: *** [_output/1-18/bin/external-attacher/linux-amd64/csi-attacher] Error 2
make: Leaving directory `/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-attacher'
```

**Review by jaxesn — COMMENTED** [review]
I dont see the golang change?

**Comment by jaxesn** [comment]
Oh i see in your commit history, im pretty sure the 1.17 version is correct.  Can you please update the updating sections of the readmes for these projects to point to the correct spot for figuring it out.  It should be this file: 

https://github.com/kubernetes-csi/external-attacher/blob/master/release-tools/prow.sh#L89

All of the sidecar repos pull those release tools and should have same file.

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
