### PR TITLE
Removed outdated user section in docs #776

### PR DESCRIPTION
**Pull request by notamyth**
Removed outdated user section in docs #776

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rothgar** [comment]
These files are still referenced in the users file. Should they be removed there? https://github.com/aws/eks-distro/blob/main/docs/contents/users/index.md

**Comment by kschumy** [comment]
@notamyth if you're ready to merge these changes, please add `/approve` to merge it. 

Thank you again for your contribution! We'll recognize your help in the next release's changelog

**Comment by kschumy** [comment]
well apparently I need to approve this too

/approve

**Pull request merged**
