### PR TITLE
fix unit test rety logic by adding gotpath to path for gotestsum

### PR DESCRIPTION
**Pull request by jaxesn**
gotestsum was being installed but was not on the PATH

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
I forced a test to failure and tested to make sure this workflow went all the way through in prow.

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Pull request merged**
