### PR TITLE
Bumped Kubernetes version to 1.20.7 and modified patches

### PR DESCRIPTION
**Pull request by kschumy**
*Description of changes:*
* Bumped Kubernetes version to 1.20.7
* Modified patches for new Kubernetes version

We will be adding another patch

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

Just in case

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
