### PR TITLE
Pause version issue

### PR DESCRIPTION
**Pull request by ahreehong**
Fixed Pause version issue: 
https://sim.amazon.com/issues/MODELROCKET-1067

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
some of the pause changes could go before 1.21 I think. This looks like 1.21 is in there, not sure what the strategy is

**Review by jaxesn — APPROVED** [review]
/lgtm

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
